#!/usr/bin/env node
/**
 * Builds src/data/quran.generated.ts from the Tanzil Quran text, so no Quran
 * text in the app is typed by hand.
 *
 *   npm run quran:import   write the file
 *   npm run quran:check    fail if the file differs from the Tanzil text
 *
 * Source: Tanzil Project Uthmani (minimal) text, version 1.1, as packaged in
 * @muslims-community/quran. Tanzil terms: the text may be copied and
 * distributed verbatim but must not be changed, and the source must be credited
 * with a link to tanzil.net. Only ayah-end markers ﴿n﴾ are added for display.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const quran = JSON.parse(readFileSync(join(root, 'node_modules/@muslims-community/quran/dist/quran.json'), 'utf8'));
const { passages } = JSON.parse(readFileSync(join(root, 'scripts/quran-passages.json'), 'utf8'));
const OUT = join(root, 'src/data/quran.generated.ts');

if (!/tanzil/i.test(quran.source) || quran.metadata.totalAyat !== 6236) {
  throw new Error(`Unexpected Quran data source: ${quran.source}`);
}

const arabicDigits = (n) => String(n).replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[d]);

function ayahText(surah, ayah) {
  const s = quran.surahs[surah - 1];
  const a = s?.ayat[ayah - 1];
  if (!a || a.id !== ayah || s.id !== surah) throw new Error(`No ayah ${surah}:${ayah}`);
  return a.text;
}

function build() {
  const out = {};
  for (const [id, parts] of Object.entries(passages)) {
    const text = parts
      .map(({ surah, ayah, fromWord = 0, toWord }) => {
        const words = ayahText(surah, ayah).split(' ');
        const last = toWord ?? words.length - 1;
        if (fromWord > last || last >= words.length) throw new Error(`${id}: words ${fromWord}–${last} outside ${surah}:${ayah}`);
        const text = words.slice(fromWord, last + 1).join(' ');
        // The ayah-end marker only goes where the ayah really ends.
        return last === words.length - 1 ? `${text} ﴿${arabicDigits(ayah)}﴾` : text;
      })
      .join(' ');
    const first = parts[0];
    const last = parts[parts.length - 1];
    const ref =
      first.surah === last.surah
        ? `${first.surah}:${first.ayah}${last.ayah !== first.ayah ? `–${last.ayah}` : ''}`
        : `${first.surah}:${first.ayah}–${last.surah}:${last.ayah}`;
    const partial = parts.some((p) => p.fromWord || p.toWord !== undefined);
    // Tanzil keeps the Basmala separate from ayah 1; pass it along for whole-surah passages.
    const bismillah = !partial && first.ayah === 1 ? quran.surahs[first.surah - 1].ayat[0].bismillah : undefined;
    out[id] = bismillah ? { text, ref, partial, bismillah } : { text, ref, partial };
  }
  return out;
}

const data = build();
const file = `// GENERATED by scripts/import-quran.mjs — do not edit by hand.
// Quran text: ${quran.source}, Uthmani minimal, version ${quran.version}.
// ${quran.copyright}. Licence: ${quran.license}. Verbatim; only ayah-end markers added.
// https://tanzil.net

export type QuranPassage = { text: string; ref: string; partial: boolean; bismillah?: string };

export const QURAN_SOURCE = 'Tanzil Project (tanzil.net), Uthmani text v${quran.version}';

export const QURAN = ${JSON.stringify(data, null, 2)} as const satisfies Record<string, QuranPassage>;
`;

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== file) {
    console.error('quran.generated.ts does not match the Tanzil text. Run: npm run quran:import');
    process.exit(1);
  }
  console.log(`OK: ${Object.keys(data).length} passages match the Tanzil text.`);
} else {
  writeFileSync(OUT, file);
  console.log(`Wrote ${Object.keys(data).length} passages to src/data/quran.generated.ts`);
}
